spring:
  main:
    web-application-type: none
    banner-mode: off
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  ai:
    mcp:
      server:
        name: widgets-mcp-server
        version: 1.0

logging:
  pattern:
    console:
  file:
    name: './widgets-mcp-server.log'